#include "d3d12_logger.h"

#include <unordered_map>

namespace {
const std::unordered_map<HRESULT, std::string_view> g_result_text{
    {S_OK, "S_OK"},
    {S_FALSE, "S_FALSE"},
    {E_NOTIMPL, "E_NOTIMPL"},
    {E_OUTOFMEMORY, "E_OUTOFMEMORY"},
    {E_INVALIDARG, "E_INVALIDARG"},
    {E_FAIL, "E_FAIL"},
    {D3D12_ERROR_ADAPTER_NOT_FOUND, "D3D12_ERROR_ADAPTER_NOT_FOUND"},
    {D3D12_ERROR_DRIVER_VERSION_MISMATCH, "D3D12_ERROR_DRIVER_VERSION_MISMATCH"},
    {DXGI_ERROR_ACCESS_DENIED, "DXGI_ERROR_ACCESS_DENIED"},
    {DXGI_ERROR_ACCESS_LOST, "DXGI_ERROR_ACCESS_LOST"},
    {DXGI_ERROR_ALREADY_EXISTS, "DXGI_ERROR_ALREADY_EXISTS"},
    {DXGI_ERROR_CANNOT_PROTECT_CONTENT, "DXGI_ERROR_CANNOT_PROTECT_CONTENT"},
    {DXGI_ERROR_DEVICE_HUNG, "DXGI_ERROR_DEVICE_HUNG"},
    {DXGI_ERROR_DEVICE_REMOVED, "DXGI_ERROR_DEVICE_REMOVED"},
    {DXGI_ERROR_DEVICE_RESET, "DXGI_ERROR_DEVICE_RESET"},
    {DXGI_ERROR_DRIVER_INTERNAL_ERROR, "DXGI_ERROR_DRIVER_INTERNAL_ERROR"},
    {DXGI_ERROR_FRAME_STATISTICS_DISJOINT, "DXGI_ERROR_FRAME_STATISTICS_DISJOINT"},
    {DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE, "DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE"},
    {DXGI_ERROR_INVALID_CALL, "DXGI_ERROR_INVALID_CALL"},
    {DXGI_ERROR_MORE_DATA, "DXGI_ERROR_MORE_DATA"},
    {DXGI_ERROR_NAME_ALREADY_EXISTS, "DXGI_ERROR_NAME_ALREADY_EXISTS"},
    {DXGI_ERROR_NONEXCLUSIVE, "DXGI_ERROR_NONEXCLUSIVE"},
    {DXGI_ERROR_NOT_CURRENTLY_AVAILABLE, "DXGI_ERROR_NOT_CURRENTLY_AVAILABLE"},
    {DXGI_ERROR_NOT_FOUND, "DXGI_ERROR_NOT_FOUND"},
    {DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED, "DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED"},
    {DXGI_ERROR_REMOTE_OUTOFMEMORY, "DXGI_ERROR_REMOTE_OUTOFMEMORY"},
    {DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE, "DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE"},
    {DXGI_ERROR_SDK_COMPONENT_MISSING, "DXGI_ERROR_SDK_COMPONENT_MISSING"},
    {DXGI_ERROR_SESSION_DISCONNECTED, "DXGI_ERROR_SESSION_DISCONNECTED"},
    {DXGI_ERROR_UNSUPPORTED, "DXGI_ERROR_UNSUPPORTED"},
    {DXGI_ERROR_WAIT_TIMEOUT, "DXGI_ERROR_WAIT_TIMEOUT"},
    {DXGI_ERROR_WAS_STILL_DRAWING, "DXGI_ERROR_WAS_STILL_DRAWING"},
};
}

std::string_view app3d::rel::d3d12::getHResultText(HRESULT result) {
    auto it = g_result_text.find(result);
    return it != g_result_text.end() ? it->second : "";
}
