#pragma once

#include "d3d12_api.h"

#include <array>

namespace app3d::rel::d3d12 {

constexpr std::array TBL_D3D12_FORMAT{
    // Format::
    DXGI_FORMAT_R32_FLOAT,           // R32_FLOAT
    DXGI_FORMAT_R32G32_FLOAT,        // R32G32_FLOAT
    DXGI_FORMAT_R32G32B32_FLOAT,     // R32G32B32_FLOAT
    DXGI_FORMAT_R32G32B32A32_FLOAT,  // R32G32B32A32_FLOAT
    DXGI_FORMAT_R8G8B8A8_UNORM,      // R8G8B8A8_UNORM
};

constexpr std::array TBL_D3D12_PRIMITIVE_TOPOLOGY{
    // PrimitiveTopology::
    D3D_PRIMITIVE_TOPOLOGY_POINTLIST,      // POINTS
    D3D_PRIMITIVE_TOPOLOGY_LINELIST,       // LINES
    D3D_PRIMITIVE_TOPOLOGY_LINESTRIP,      // LINE_STRIP
    D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST,   // TRIANGLES
    D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,  // TRIANGLE_STRIP
};

constexpr std::array TBL_D3D12_VISIBILITY{
    // ShaderStage::
    D3D12_SHADER_VISIBILITY_ALL,     // ALL_STAGES
    D3D12_SHADER_VISIBILITY_VERTEX,  // VERTEX_SHADER
    D3D12_SHADER_VISIBILITY_PIXEL,   // PIXEL_SHADER
};

constexpr std::array TBL_D3D12_DESC_TYPES{
    // BindingType::
    D3D12_DESCRIPTOR_RANGE_TYPE_CBV,      // CONSTANT_BUFFER
    D3D12_DESCRIPTOR_RANGE_TYPE_SRV,      // SHADER_RESOURCE
    D3D12_DESCRIPTOR_RANGE_TYPE_UAV,      // UNORDERED
    D3D12_DESCRIPTOR_RANGE_TYPE_SAMPLER,  // SAMPLER
};

constexpr std::array TBL_D3D12_FILTER{
    // SamplerFilter::
    D3D12_FILTER_MIN_MAG_MIP_POINT,                // MIN_MAG_MIP_POINT
    D3D12_FILTER_MIN_MAG_POINT_MIP_LINEAR,         // MIN_MAG_POINT_MIP_LINEAR
    D3D12_FILTER_MIN_POINT_MAG_LINEAR_MIP_POINT,   // MIN_POINT_MAG_LINEAR_MIP_POINT
    D3D12_FILTER_MIN_POINT_MAG_MIP_LINEAR,         // MIN_POINT_MAG_MIP_LINEAR
    D3D12_FILTER_MIN_LINEAR_MAG_MIP_POINT,         // MIN_LINEAR_MAG_MIP_POINT
    D3D12_FILTER_MIN_LINEAR_MAG_POINT_MIP_LINEAR,  // MIN_LINEAR_MAG_POINT_MIP_LINEAR
    D3D12_FILTER_MIN_MAG_LINEAR_MIP_POINT,         // MIN_MAG_LINEAR_MIP_POINT
    D3D12_FILTER_MIN_MAG_MIP_LINEAR,               // MIN_MAG_MIP_LINEAR
    D3D12_FILTER_ANISOTROPIC,                      // ANISOTROPIC
};

constexpr std::array TBL_D3D12_ADDRESS_MODE{
    // SamplerAddressMode::
    D3D12_TEXTURE_ADDRESS_MODE_WRAP,         // REPEAT
    D3D12_TEXTURE_ADDRESS_MODE_MIRROR,       // MIRRORED_REPEAT
    D3D12_TEXTURE_ADDRESS_MODE_CLAMP,        // CLAMP_TO_EDGE
    D3D12_TEXTURE_ADDRESS_MODE_MIRROR_ONCE,  // MIRROR_CLAMP_TO_EDGE
};

}  // namespace app3d::rel::d3d12
