#ifndef EXPORTED_VK_FUNCTION
#    define EXPORTED_VK_FUNCTION(function)
#endif

EXPORTED_VK_FUNCTION(vkGetInstanceProcAddr);

#undef EXPORTED_VK_FUNCTION

// --------------------------------------------------------

#ifndef GLOBAL_LEVEL_VK_FUNCTION
#    define GLOBAL_LEVEL_VK_FUNCTION(function)
#endif

GLOBAL_LEVEL_VK_FUNCTION(vkEnumerateInstanceExtensionProperties);
GLOBAL_LEVEL_VK_FUNCTION(vkEnumerateInstanceLayerProperties);
GLOBAL_LEVEL_VK_FUNCTION(vkCreateInstance);

#undef GLOBAL_LEVEL_VK_FUNCTION

// --------------------------------------------------------

#ifndef INSTANCE_LEVEL_VK_FUNCTION
#    define INSTANCE_LEVEL_VK_FUNCTION(function)
#endif

INSTANCE_LEVEL_VK_FUNCTION(vkDestroyInstance);
INSTANCE_LEVEL_VK_FUNCTION(vkEnumeratePhysicalDevices);
INSTANCE_LEVEL_VK_FUNCTION(vkEnumerateDeviceExtensionProperties);
INSTANCE_LEVEL_VK_FUNCTION(vkGetPhysicalDeviceProperties);
INSTANCE_LEVEL_VK_FUNCTION(vkGetPhysicalDeviceFeatures);
INSTANCE_LEVEL_VK_FUNCTION(vkGetPhysicalDeviceQueueFamilyProperties);
INSTANCE_LEVEL_VK_FUNCTION(vkCreateDevice);
INSTANCE_LEVEL_VK_FUNCTION(vkGetDeviceProcAddr);

#undef INSTANCE_LEVEL_VK_FUNCTION

// --------------------------------------------------------

#ifndef INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION
#    define INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION(function, extension)
#endif

INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkGetPhysicalDeviceSurfaceSupportKHR, VK_KHR_SURFACE_EXTENSION_NAME);
INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkGetPhysicalDeviceSurfacePresentModesKHR, VK_KHR_SURFACE_EXTENSION_NAME);
INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkGetPhysicalDeviceSurfaceCapabilitiesKHR, VK_KHR_SURFACE_EXTENSION_NAME);
INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkGetPhysicalDeviceSurfaceFormatsKHR, VK_KHR_SURFACE_EXTENSION_NAME);
#if defined(VK_USE_PLATFORM_WIN32_KHR)
INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkCreateWin32SurfaceKHR, VK_KHR_WIN32_SURFACE_EXTENSION_NAME);
#elif defined(VK_USE_PLATFORM_XLIB_KHR)
INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkCreateXlibSurfaceKHR, VK_KHR_XLIB_SURFACE_EXTENSION_NAME);
#elif defined(VK_USE_PLATFORM_XCB_KHR)
INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkCreateXcbSurfaceKHR, VK_KHR_XCB_SURFACE_EXTENSION_NAME);
#elif defined(VK_USE_PLATFORM_WAYLAND_KHR)
INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkCreateWaylandSurfaceKHR, VK_KHR_WAYLAND_SURFACE_EXTENSION_NAME);
#endif

#undef INSTANCE_LEVEL_VK_FUNCTION_FROM_EXTENSION

// --------------------------------------------------------

#ifndef DEVICE_LEVEL_VK_FUNCTION
#    define DEVICE_LEVEL_VK_FUNCTION(function)
#endif

DEVICE_LEVEL_VK_FUNCTION(vkDestroyDevice);
DEVICE_LEVEL_VK_FUNCTION(vkGetDeviceQueue);
DEVICE_LEVEL_VK_FUNCTION(vkDeviceWaitIdle);
DEVICE_LEVEL_VK_FUNCTION(vkCreateBuffer);
DEVICE_LEVEL_VK_FUNCTION(vkGetBufferMemoryRequirements);

#undef DEVICE_LEVEL_VK_FUNCTION

// --------------------------------------------------------

#ifndef DEVICE_LEVEL_VK_FUNCTION_FROM_EXTENSION
#    define DEVICE_LEVEL_VK_FUNCTION_FROM_EXTENSION(function, extension)
#endif

DEVICE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkCreateSwapchainKHR, VK_KHR_SWAPCHAIN_EXTENSION_NAME);
DEVICE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkGetSwapchainImagesKHR, VK_KHR_SWAPCHAIN_EXTENSION_NAME);
DEVICE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkAcquireNextImageKHR, VK_KHR_SWAPCHAIN_EXTENSION_NAME);
DEVICE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkQueuePresentKHR, VK_KHR_SWAPCHAIN_EXTENSION_NAME);
DEVICE_LEVEL_VK_FUNCTION_FROM_EXTENSION(vkDestroySwapchainKHR, VK_KHR_SWAPCHAIN_EXTENSION_NAME);

#undef DEVICE_LEVEL_VK_FUNCTION_FROM_EXTENSION
